# Menu configuration
menu:
  Home: /
  Archives: /archives
  About: /about

# Favicon configuration
favicon: /favicon.ico

# Social links
links:
  github: https://github.com/mangege
  twitter: https://x.com/ciro9526

# RSS link (match the one in _config.yml)
rss: /atom.xml

# Analytics
google_analytics: UA-105681387-1
